ecommerce_shop_project/account/urls.py
from django.urls import path

from .views import (
    register,
    UserLoginView,
    UserLogoutView,
    profile,
    ProfileUpdateView,
    AccountPasswordChangeView,
    AccountPasswordResetView,
    AccountPasswordResetDoneView,
    AccountPasswordResetConfirm,
    AccoutnPasswordResetCompleteView,
    order_detail,
)

app_name = "account"
urlpatterns = [
    path("register/", register, name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    # profile
    path("profile/", profile, name="profile"),
    path("profile_edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path(
        "password_change/", AccountPasswordChangeView.as_view(), name="password_change"
    ),
    # password reset
    path("password_reset/", AccountPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        AccountPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        AccountPasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        AccoutnPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("order_detail/<int:pk>", order_detail, name="order_detail"),
]

ecommerce_shop_project/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<product_id>/", views.cart_add, name="cart_add"),
    path("remove/<product_id>/", views.cart_remove, name="cart_remove"),
]

ecommerce_shop_project/ecommerce_shop_project/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("cart", include("cart.urls")),
    path("contact/", include("contact.urls")),
    path("", include(("shop.urls", "shop"), namespace="shop")),
    path("account/", include(("account.urls", "account"), namespace="account")),
    path("staff/", include(("staff.urls", "staff"), namespace="staff")),
    path('orders/', include('orders.urls')),
    path('dynamic_cart/', include("dynamic_cart.urls")),
    path('subscription/', include('subscription.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ecommerce_shop_project/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("product/<str:slug>/", views.product_detail, name="product_detail"),
    path(
        "category/<str:name>/",
        views.CategoryProductView.as_view(),
        name="category_product",
    ),
    path("edit_comment/<int:comment_pk>/", views.process_comment, name="edit_comment"),
    path("add_comment/<int:product_pk>/", views.process_comment, name="add_comment"),
    path("about/", views.about, name="about"),
    path("like_product/<product_id>", views.like_product, name="like_product"),
    path(
        "add_rating/<product_id>/<int:stars>", views.process_rating, name="add_rating"
    ),
]

ecommerce_shop_project/staff/urls.py
from django.urls import path
from .views import (
    PanelView,
    ProductListView,
    ProductImageListView,
    CategoryListView,
    CommentListView,
    UserListView,
    OrderListView,
    OrderDetailView,
    AddProductView,
    AddProductImageView,
    AddCategoryView,
    UpdateProductView,
    UpdateProductImageView,
    UpdateCategoryView,
    DeleteProductView,
    DeleteProductImageView,
    DeleteCategoryView,
    UserDetailView,
    CommentDetailView,
    toggle_comment_activity,
    discount_product,
    delete_product_discount,
    discount_category,
    delete_category_discount,
    list_from_api,
    AddProductFromApi,
)
from .decorators import staff_required

app_name = "staff"
urlpatterns = [
    path("", staff_required(PanelView.as_view()), name="panel"),
    # list
    path(
        "product_list", staff_required(ProductListView.as_view()), name="product_list"
    ),
    path(
        "product_images_list",
        staff_required(ProductImageListView.as_view()),
        name="product_images_list",
    ),
    path(
        "categories_list",
        staff_required(CategoryListView.as_view()),
        name="category_list",
    ),
    path(
        "comment_list", staff_required(CommentListView.as_view()), name="comment_list"
    ),
    path("list_from_api", staff_required(list_from_api), name="list_from_api"),
    path("order_list", staff_required(OrderListView.as_view()), name="order_list"),
    path("user_list", staff_required(UserListView.as_view()), name="user_list"),
    # add
    path(
        "add_from_api/<str:id>",
        staff_required(AddProductFromApi.as_view()),
        name="add_from_api",
    ),
    path("add_product", staff_required(AddProductView.as_view()), name="add_product"),
    path(
        "add_product_image",
        staff_required(AddProductImageView.as_view()),
        name="add_product_image",
    ),
    path(
        "add_category", staff_required(AddCategoryView.as_view()), name="add_category"
    ),
    # edit
    path(
        "update_product/<int:pk>",
        staff_required(UpdateProductView.as_view()),
        name="update_product",
    ),
    path(
        "update_product_image/<int:pk>",
        staff_required(UpdateProductImageView.as_view()),
        name="update_product_image",
    ),
    path(
        "update_category/<int:pk>",
        staff_required(UpdateCategoryView.as_view()),
        name="update_category",
    ),
    # delete
    path(
        "delete_product/<int:pk>",
        staff_required(DeleteProductView.as_view()),
        name="delete_product",
    ),
    path(
        "delete_product_image/<int:pk>",
        staff_required(DeleteProductImageView.as_view()),
        name="delete_product_image",
    ),
    path(
        "delete_category/<int:pk>",
        staff_required(DeleteCategoryView.as_view()),
        name="delete_category",
    ),
    path(
        "delete_product_discount/<int:pk>/",
        staff_required(delete_product_discount),
        name="delete_product_discount",
    ),
    path(
        "delete_category_discount/<int:pk>/",
        staff_required(delete_category_discount),
        name="delete_category_discount",
    ),
    # detail
    path(
        "user_detail/<int:pk>",
        staff_required(UserDetailView.as_view()),
        name="user_detail",
    ),
    path(
        "comment_detail/<int:pk>",
        staff_required(CommentDetailView.as_view()),
        name="comment_detail",
    ),
    path(
        "order_detail/<int:pk>",
        staff_required(OrderDetailView.as_view()),
        name="order_detail",
    ),
    path(
        "comment_detail/<int:pk>",
        staff_required(CommentDetailView.as_view()),
        name="comment_detail",
    ),
    # other
    path(
        "toggle_comment/<int:pk>",
        staff_required(toggle_comment_activity),
        name="toggle_comment",
    ),
    path(
        "discount_product/<int:pk>",
        staff_required(discount_product),
        name="discount_product",
    ),
    path(
        "discount_category/<int:pk>",
        staff_required(discount_category),
        name="discount_category",
    ),
]

ecommerce_shop_project/orders/models.py
from django.db import models
from shop.models import Product
from account.models import Address, User


class Order(models.Model):

    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return "Order {}".format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return "{}".format(self.id)

    def get_cost(self):
        return self.price * self.quantity

ecommerce_shop_project/staff/forms.py
from django import forms
from django.utils import timezone

from shop.models import Comment, ProductDiscount, CategoryDiscount
from orders.models import Order


class PublishCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["is_active"]
        labels = {"is_active": ""}


class OrderPayForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["paid"]
        labels = {"paid": ""}


class DiscountProductForm(forms.ModelForm):

    start_time = forms.DateTimeField(initial=timezone.now)
    discount_percent = forms.IntegerField(max_value=100, min_value=0)

    class Meta:
        model = ProductDiscount
        fields = ["discount_percent", "start_time", "end_time"]


class DiscountCategoryForm(forms.ModelForm):

    start_time = forms.DateTimeField(initial=timezone.now)
    discount_percent = forms.IntegerField(max_value=100, min_value=0)

    class Meta:
        model = CategoryDiscount
        fields = ["discount_percent", "start_time", "end_time"]

ecommerce_shop_project/staff/templates/staff/add_product_image.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<div>
    <h2>Add product image:</h2>
    <div class="row">
        <div class="col">
            <a href="{% url 'staff:product_images_list' %}" class="btn btn-info">Go back</a>
        </div>
    </div>
</div>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        {{form|crispy}}
    </fieldset>
    <div>
        <button type="submit" class="btn btn-info">Add</button>
    </div>
</form>
{% endblock %}

ecommerce_shop_project/staff/templates/staff/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Staff Panel</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    {% block extrastyle %}
    {% endblock %}
    <link href="{% static 'css/staff.css' %}" rel="stylesheet">


</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'staff:panel' %}">Staff Panel</a>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">

                </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'account:profile'%}">
                        Welcome, {{ user.email }}
                    </a>
                    <a class="nav-item nav-link" href="{% url 'shop:index'%}"> go to page </a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container" style="min-height: 1000px;">




        {% block content%}


        {% endblock%}


        <!-- /.row -->

    </div>

    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Samochody z Niemiec 2019</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


</body>

</html>

ecommerce_shop_project/staff/templates/staff/category_list.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col">
        <div>
            <h2>Categories</h2>
            <div class="row">
                <div class="col">
                    <a href="{%url 'staff:panel'%}" class="btn btn-info"">Go back</a>
                </div>
                <div class=" col text-right">
                        <a href="{%url 'staff:add_category'%}" class="btn btn-info">Add category</a>
                </div>
            </div>
        </div>
        {% with categories.count as total_categories %}
        <small>Total categories: {{total_categories}} </small>
        {% endwith%}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Products quantity</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td>{{category.name}}</td>
                    <td>{{category.prod_count}}</td>
                    <td></td>
                    <td></td>
                    <td><a href="{% url 'staff:update_category' pk=category.pk %}" class="btn btn-secondary">Edit</a>
                    </td>
                    <td><a href="{%url 'staff:discount_category' pk=category.pk%}" class="btn btn-info">Discount</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/comment_detail.html
{% extends 'staff/base.html' %}

{% block content %}


<div class="row">
    <div class="col">
        <a href="{% url 'staff:comment_list'%}" class="btn btn-info">Go back</a>
    </div>
</div>

<div class="col-12">
    <div class="tab-content ml-1" id="commentContent">


        <div class="row">
            <div class="col-sm-3 col-md-2 col-5">
                <label style="font-weight:bold;">Product</label>
            </div>
            <div class="col-md-8 col-6">
                {{ object.product.name }}
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col-sm-3 col-md-2 col-5">
                <label style="font-weight:bold;">User</label>
            </div>
            <div class="col-md-8 col-6">
                {{ object.user }}
            </div>
        </div>
        <hr />

        <div class="row">
            <div class="col-sm-3 col-md-2 col-5">
                <label style="font-weight:bold;">Created</label>
            </div>
            <div class="col-md-8 col-6">
                {{object.date_created}}
            </div>
        </div>
        <hr />
        <div class="row">
            <div class="col-sm-3 col-md-2 col-5">
                <label style="font-weight:bold;">Body</label>
            </div>
            <div class="col-md-8 col-6">
                {{object.body}}
            </div>

        </div>
        <hr />

        <div class="row">
            <div class="col-sm-3 col-md-2 col-5">
                <label style="font-weight:bold;">Published</label>
            </div>
            <div class="col-md-8 col-6">
                <form id='publishCommentForm' method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                </form>
            </div>

        </div>
        <hr />


        <input value="Save" type="submit" form="publishCommentForm" class="btn btn-info" />

    </div>
</div>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/comment_list.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col">
        <div>
            <h2>Comments</h2>
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url 'staff:panel' %}" class="btn btn-info">Go back</a>
            </div>
        </div>
        {% with comments.count as total_comments %}
        <small>Total comments: {{total_comments}} </small>
        {% endwith%}



        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Product name</th>
                    <th scope="col">User</th>
                    <th scope="col">Date created</th>
                    <th scope="col">Published</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for comment in comments %}
                <tr class="{% if comment.is_new %} table-primary {% endif %}">
                    <td>{{comment.product.name}} </td>
                    <td>{{comment.user}}</td>
                    <td>{{comment.date_created}}</td>
                    <td>{% if comment.is_active %} &check;
                        {% else %}
                        &cross;
                        {% endif%}</td>
                    <td><a href="{% url 'staff:comment_detail' pk=comment.pk %}" class="btn btn-secondary">Detail</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/delete_category.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<h2>Delete {{category.name}}:</h2>

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ category.name }}"?
        This will delete all related products!!!
    </p>
    <input type=button class="btn btn-info" value="Go Back" onClick="javascript:history.go(-1);">
    <input class="btn btn-danger text-right" type="submit" value="Confirm">
</form>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/delete_product_image.html
{% extends 'staff/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<h2>Delete {{productimage}}:</h2>

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete this image <img src="{{productimage.image.url}}" width="100" height="160"></td> ?</p>
    <input type=button class="btn btn-info" value="Go Back" onClick="javascript:history.go(-1);">
    <input class="btn btn-danger text-right" type="submit" value="Confirm">

</form>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/discount_category.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<h2>Discount {{category.name}}:</h2>
<div class="row">
    <div class="col">
        <a href="{% url 'staff:category_list' %}" class="btn btn-info">Go back</a>
    </div>
</div>

<div class="discounts-list">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Start</th>
                <th scope="col">End</th>
                <th scope="col">Discount percent</th>
                <th scope="col">Discount type</th>
            </tr>
        </thead>
        <tbody>
            {% for discount in discounts %}
            {% if discount.is_active %}
            <tr>
                <td>{{discount.start_time}} </td>
                <td>{{discount.end_time}}</td>
                <td>{{discount.discount_percent}} &percnt;</td>
                <td>
                    <form method="GET" action="{% url 'staff:delete_category_discount' pk=discount.pk  %}"><input
                            type="submit" class="btn btn-danger" value="delete"></form>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
<h2>Add new discount</h2>

<form id="discount-form" method="POST">
    {% csrf_token %}
    <fieldset>
        {{form|crispy}}
    </fieldset>
    <div>
        <button type="submit" class="btn btn-info">Add</button>
    </div>
</form>
{% endblock %}

ecommerce_shop_project/staff/templates/staff/discount_product.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<h2>Discount {{product.name}}:</h2>
<div class="row">
    <div class="col">
        <a href="{% url 'staff:product_list' %}" class="btn btn-info">Go back</a>
    </div>
</div>

<div class="discounts-list">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">start</th>
                <th scope="col">end</th>
                <th scope="col">discount percent</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for discount in discounts %}
            {% if discount.is_active %}
            <tr>
                <td>{{discount.start_time}} </td>
                <td>{{discount.end_time}}</td>
                <td>{{discount.discount_percent}} &percnt;</td>
                <td>{% if discount.category_discount %}
                    category discount
                    {% else %}
                    product discount
                    {% endif %}
                </td>
                <td>
                    <form method="GET" action="{% url 'staff:delete_product_discount' pk=discount.pk  %}"><input
                            type="submit" class="btn btn-danger" value="delete"></form>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>
<h2>Add new discount</h2>

<form id="discount-form" method="POST">
    {% csrf_token %}
    <fieldset>
        {{form|crispy}}
    </fieldset>
    <div>
        <button type="submit" class="btn btn-info">Add</button>
    </div>
</form>
{% endblock %}

ecommerce_shop_project/staff/templates/staff/list_from_api.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col">
        <div>
            <h2>Add products using google books</h2>
            <div class="row">
                <div class="col">
                    <a href="{% url 'staff:product_list' %}" class="btn btn-info">Go back</a>
                </div>
            </div>
        </div>

        <form action="{% url 'staff:list_from_api' %}" method="get">
            <input type="text" name="q" class="search" value="{% if query %}{{ query }}{% endif %}">
            <button type="submit" class="btn-dark">Search</button>
            {% if query %}
            <button type="submit" formmethod="post" class="close-icon" name="clear-button"></button>
            {% csrf_token %}
            {% endif %}
        </form>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Author</th>
                    <th scope="col">Description</th>
                    <th scope="col"></th>

                </tr>
            </thead>
            <tbody>
                {% for book in books%}
                <tr>
                    <td>{{book.title|truncatewords:7}} </td>
                    <td>{{book.authors|join:"; "}} </td>
                    <td>{{book.desc|yesno:"yes,no"}} </td>
                    <td><a href="{% url 'staff:add_from_api' id=book.id %}" class="btn btn-info">add</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/order_detail.html
{% extends 'staff/base.html' %}

{% load static %}

{% block extrastyle %}
<link href="{% static 'css/order.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="row">
    <div class="col">
        <a href="{%url 'staff:order_list'%}" class="btn btn-info"">Go back</a>
    </div>
    <div class=" col text-right">
            <a class="btn btn-info" href="#" onclick="window.print();">Print</a>
    </div>
</div>

<h1>Order no. {{ order.id }}</h1>

<table class="table">
    <tr>
        <th>Created</th>
        <td>{{ order.created }}</td>
    </tr>
    <tr>
        <th>Client</th>
        <td>{{ order.address.name }}</td>
    </tr>
    <tr>
        <th>E-mail</th>
        <td><a href="mailto:{{ order.email }}">{{ order.user }}</a></td>
    </tr>
    <tr>
        <th>Adress</th>
        <td>{{ order.address.street }} <br>
            {{ order.address.postal_code }} {{ order.address.city }} <br>
            {{ order.address.country }} <br> </td>
    </tr>
    <tr>
        <th>Total value</th>
        <td>${{ order.get_total_cost }} </td>
    </tr>
    <tr>
        <th>Paid</th>
        <td>
            <form id='pay' method="POST">
                {% csrf_token %}
                {{form.as_p}}
            </form>
        </td>
    </tr>
</table>
<input value="Save" type="submit" form="pay" class="btn btn-info" />


<table class="table table-bordered">
    <h2>Items</h2>
    <thead>
        <tr>
            <th scope="col">Product</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
        <tr>
            <td>{{ item.product.name }}</td>
            <td class="num">${{ item.price }}</td>
            <td class="num">{{ item.quantity }}</td>
            <td class="num">${{ item.get_cost }}</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3"></td>
        </tr>
        <tr class="total">
            <td colspan="3">Total</td>
            <td class="num">${{ order.get_total_cost }}</td>
        </tr>
    </tbody>
</table>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/product_images_list.html
{% extends 'staff/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col">
        <div>
            <h2>Products' Images</h2>
            <div class="row">
                <div class="col">
                    <a href="{% url 'staff:panel' %}" class="btn btn-info">Go back</a>
                </div>
                <div class="col text-right">
                    <a href="{%url 'staff:add_product_image'%}" class="btn btn-info">Add image</a>
                </div>
            </div>
        </div>



        #{% with product_images.count as total_images %}
        <small>Total: {{total_images}} </small>
        {% endwith%}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Image</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for image in product_images %}
                <tr>
                    <td>{{image.product.name}} </td>
                    <td><a href="{{ image.product.get_absolute_url }}"><img src="{{image.image.url}}" width="50" height="80"></a></td>
                    <td><a href="{%url 'staff:delete_product_image' pk=image.pk%}" class="btn btn-secondary">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

ecommerce_shop_project/staff/templates/staff/update_product.html
{% extends 'staff/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<h2>Update {{product.name}}:</h2>
<div class="row">
    <div class="col">
        <a href="{% url 'staff:product_list' %}" class="btn btn-info">Go back</a>
    </div>
    <div class="col text-right">
        <a href="{%url 'staff:delete_product' pk=product.pk%}" class="btn btn-danger">Delete product</a>
    </div>
</div>



<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        {{form|crispy}}
    </fieldset>
    <div>
        <button type="submit" class="btn btn-info">Update</button>
    </div>
</form>
{% endblock %}

ecommerce_shop_project/staff/templates/staff/user_detail.html
{% extends 'staff/base.html' %}

{% block content %}

<h2>User {{user.email}}</h2>
<div class="row">
    <div class="col">
        <a href="{% url 'staff:user_list'%}" class="btn btn-info">Go back</a>
    </div>
</div>
<div class="d-flex justify-content-start">
    <div class="image-container">
        <img src="http://placehold.it/150x150" id="imgProfile" style="width: 150px; height: 150px"
            class="img-thumbnail" />
    </div>
    <div class="userData ml-3">
        <table class="table">
            <tr>
                <th>Created</th>
                <td>{{ user.created }}</td>
            </tr>
        </table>
    </div>
</div>
<div class="col-12">
    <div class="tab-content ml-1" id="myTabContent">


        <h3>Orders placed</h3>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Date created</th>
                    <th scope="col">Order state</th>
                    <th scope="col">User</th>
                    <th scope="col">Total value</th>
                </tr>
            </thead>
            <tbody>
                {% for order in user.order_set.all %}
                <tr>
                    <td>{{order.id}} </td>
                    <td>{{order.created}}</td>
                    <td>{% if order.paid %}Paid{% else %}Waiting for payment
                        {% endif %}</td>
                    <td>{{order.user}}</td>
                    <td> {{order.get_total_cost}}</td>

                    <td><a href="{% url 'staff:order_detail' pk=order.pk %}" class="btn btn-secondary">Detail</a></td>

                </tr>
                {% endfor %}
            </tbody>
        </table>


    </div>
</div>

{% endblock %}