ecommerce_shop_project/account/urls.py
from django.urls import path

from .views import (
    register,
    UserLoginView,
    UserLogoutView,
    profile,
    ProfileUpdateView,
    AccountPasswordChangeView,
    AccountPasswordResetView,
    AccountPasswordResetDoneView,
    AccountPasswordResetConfirm,
    AccoutnPasswordResetCompleteView,
    order_detail,
)

app_name = "account"
urlpatterns = [
    path("register/", register, name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    # profile
    path("profile/", profile, name="profile"),
    path("profile_edit/", ProfileUpdateView.as_view(), name="profile_edit"),
    path(
        "password_change/", AccountPasswordChangeView.as_view(), name="password_change"
    ),
    # password reset
    path("password_reset/", AccountPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        AccountPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        AccountPasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        AccoutnPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("order_detail/<int:pk>", order_detail, name="order_detail"),
]

ecommerce_shop_project/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<product_id>/", views.cart_add, name="cart_add"),
    path("remove/<product_id>/", views.cart_remove, name="cart_remove"),
]

ecommerce_shop_project/contact/urls.py
from django.conf.urls import url
from . import views

app_name = "contact"

urlpatterns = [
    url(r"^$", views.contact, name="contact"),
]

ecommerce_shop_project/ecommerce_shop_project/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("cart", include("cart.urls")),
    path("contact/", include("contact.urls")),
    path("", include(("shop.urls", "shop"), namespace="shop")),
    path("account/", include(("account.urls", "account"), namespace="account")),
    path("staff/", include(("staff.urls", "staff"), namespace="staff")),
    path('orders/', include('orders.urls')),
    path('dynamic_cart/', include("dynamic_cart.urls")),
    path('subscription/', include('subscription.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ecommerce_shop_project/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("product/<str:slug>/", views.product_detail, name="product_detail"),
    path(
        "category/<str:name>/",
        views.CategoryProductView.as_view(),
        name="category_product",
    ),
    path("edit_comment/<int:comment_pk>/", views.process_comment, name="edit_comment"),
    path("add_comment/<int:product_pk>/", views.process_comment, name="add_comment"),
    path("about/", views.about, name="about"),
    path("like_product/<product_id>", views.like_product, name="like_product"),
    path(
        "add_rating/<product_id>/<int:stars>", views.process_rating, name="add_rating"
    ),
]

ecommerce_shop_project/staff/urls.py
from django.urls import path
from .views import (
    PanelView,
    ProductListView,
    ProductImageListView,
    CategoryListView,
    CommentListView,
    UserListView,
    OrderListView,
    OrderDetailView,
    AddProductView,
    AddProductImageView,
    AddCategoryView,
    UpdateProductView,
    UpdateProductImageView,
    UpdateCategoryView,
    DeleteProductView,
    DeleteProductImageView,
    DeleteCategoryView,
    UserDetailView,
    CommentDetailView,
    toggle_comment_activity,
    discount_product,
    delete_product_discount,
    discount_category,
    delete_category_discount,
    list_from_api,
    AddProductFromApi,
)
from .decorators import staff_required

app_name = "staff"
urlpatterns = [
    path("", staff_required(PanelView.as_view()), name="panel"),
    # list
    path(
        "product_list", staff_required(ProductListView.as_view()), name="product_list"
    ),
    path(
        "product_images_list",
        staff_required(ProductImageListView.as_view()),
        name="product_images_list",
    ),
    path(
        "categories_list",
        staff_required(CategoryListView.as_view()),
        name="category_list",
    ),
    path(
        "comment_list", staff_required(CommentListView.as_view()), name="comment_list"
    ),
    path("list_from_api", staff_required(list_from_api), name="list_from_api"),
    path("order_list", staff_required(OrderListView.as_view()), name="order_list"),
    path("user_list", staff_required(UserListView.as_view()), name="user_list"),
    # add
    path(
        "add_from_api/<str:id>",
        staff_required(AddProductFromApi.as_view()),
        name="add_from_api",
    ),
    path("add_product", staff_required(AddProductView.as_view()), name="add_product"),
    path(
        "add_product_image",
        staff_required(AddProductImageView.as_view()),
        name="add_product_image",
    ),
    path(
        "add_category", staff_required(AddCategoryView.as_view()), name="add_category"
    ),
    # edit
    path(
        "update_product/<int:pk>",
        staff_required(UpdateProductView.as_view()),
        name="update_product",
    ),
    path(
        "update_product_image/<int:pk>",
        staff_required(UpdateProductImageView.as_view()),
        name="update_product_image",
    ),
    path(
        "update_category/<int:pk>",
        staff_required(UpdateCategoryView.as_view()),
        name="update_category",
    ),
    # delete
    path(
        "delete_product/<int:pk>",
        staff_required(DeleteProductView.as_view()),
        name="delete_product",
    ),
    path(
        "delete_product_image/<int:pk>",
        staff_required(DeleteProductImageView.as_view()),
        name="delete_product_image",
    ),
    path(
        "delete_category/<int:pk>",
        staff_required(DeleteCategoryView.as_view()),
        name="delete_category",
    ),
    path(
        "delete_product_discount/<int:pk>/",
        staff_required(delete_product_discount),
        name="delete_product_discount",
    ),
    path(
        "delete_category_discount/<int:pk>/",
        staff_required(delete_category_discount),
        name="delete_category_discount",
    ),
    # detail
    path(
        "user_detail/<int:pk>",
        staff_required(UserDetailView.as_view()),
        name="user_detail",
    ),
    path(
        "comment_detail/<int:pk>",
        staff_required(CommentDetailView.as_view()),
        name="comment_detail",
    ),
    path(
        "order_detail/<int:pk>",
        staff_required(OrderDetailView.as_view()),
        name="order_detail",
    ),
    path(
        "comment_detail/<int:pk>",
        staff_required(CommentDetailView.as_view()),
        name="comment_detail",
    ),
    # other
    path(
        "toggle_comment/<int:pk>",
        staff_required(toggle_comment_activity),
        name="toggle_comment",
    ),
    path(
        "discount_product/<int:pk>",
        staff_required(discount_product),
        name="discount_product",
    ),
    path(
        "discount_category/<int:pk>",
        staff_required(discount_category),
        name="discount_category",
    ),
]

ecommerce_shop_project/subscription/urls.py
from django.urls import path
from . import views

app_name = "subscription"

urlpatterns = [
    path("", views.subscription, name="subscription"),
    path("success/", views.success_view, name="success"),
]

ecommerce_shop_project/shop/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["body"]

ecommerce_shop_project/shop/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Product, Category, Comment, Rating, Like
from cart.forms import CartAddProductForm
from .forms import CommentForm
from django.http import JsonResponse


OBJECTS_PER_PAGE = 2


def populate_products_add_ratings(products):
    for product in products:
        stars, empty_stars = count_stars(product)
        product.stars = range(stars)
        product.empty_stars = range(empty_stars)
    return products


def count_stars(product):
    # star rating
    if product.count_rating:
        rating = int(product.total_rating / product.count_rating)
        return rating, 5 - rating
    return 0, 5


class IndexView(ListView):
    model = Category
    template_name = "shop/index.html"
    context_object_name = "category_list"

    def post(self, *args, **kwargs):
        return self.get(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        query = self.request.GET.get("q")
        products = Product.objects.all()
        if query:
            products = products.filter(name__contains=query)

        page = self.request.GET.get("page", 1)
        paginator = Paginator(products, OBJECTS_PER_PAGE)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        populate_products_add_ratings(products)
        context["products"] = products
        context["query"] = query

        return context


class CategoryProductView(ListView):
    template_name = "shop/category_products.html"
    context_object_name = "products"
    paginate_by = OBJECTS_PER_PAGE

    def get_queryset(self):
        self.category = get_object_or_404(Category, name=self.kwargs["name"])
        products = self.category.product_set.all()
        populate_products_add_ratings(products)
        return products

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["category_list"] = Category.objects.all()
        context["category"] = self.category
        return context


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    cart_product_form = CartAddProductForm()
    category_list = Category.objects.all()
    # comments
    comments = product.comment_set.all().prefetch_related("user")
    likes = product.likes
    stars, empty_stars = count_stars(product)
    form = CommentForm()
    context = {
        "product": product,
        "category_list": category_list,
        "stars": range(stars),
        "empty_stars": range(empty_stars),
        "comments": comments,
        "form": form,
        "rating": stars,
        "cart_product_form": cart_product_form,
        "likes": likes,
    }
    return render(request, "shop/product_detail.html", context=context)


def about(request):
    category_list = Category.objects.all()
    cart_product_form = CartAddProductForm()
    context = {"category_list": category_list, "cart_product_form": cart_product_form}
    return render(request, "shop/about.html", context=context)


@login_required
@require_POST
def process_comment(request, product_pk=None, comment_pk=None):
    form = CommentForm(request.POST)
    if form.is_valid():
        print("valid")
        if product_pk:
            product = get_object_or_404(Product, pk=product_pk)

            new_comment = form.save(commit=False)
            new_comment.product = product
            new_comment.user = request.user
            new_comment.save()
        elif comment_pk:
            comment = get_object_or_404(Comment, pk=comment_pk)
            form = CommentForm(request.POST, instance=comment)
            form.save()
            product = comment.product

        # after submin redirect to porduct page
    return redirect(product)  # same as product.get_absolute_url


@login_required
@csrf_exempt
def process_rating(request, product_id, stars):
    product = get_object_or_404(Product, id=product_id)
    user = request.user
    if not Rating.objects.filter(product=product, user=user).exists():
        product.total_rating += stars + 1
        product.count_rating += 1
        product.save()
        Rating.objects.create(product=product, user=user)
    stars, _ = count_stars(product)
    return JsonResponse({"stars": stars})


@login_required
@csrf_exempt
def like_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    user = request.user
    likes = product.likes
    if not Like.objects.filter(product=product, user=user).exists():
        likes = likes + 1
        product.likes = likes
        product.save()
        Like.objects.create(product=product, user=user)
    return HttpResponse(likes)

ecommerce_shop_project/shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content%}

<div class="content">
    <div class="title">
        <p>Ecommerce bookshop Bookworm is a design-minded, multi-disciplinary brand offering
            experiences
            related to
            books and reading. We are based in Wroclaw, Poland.
        </p>
    </div>
    <div class="philosophy">
        <p>OUR PHILOSOPHY</p>
    </div>
    <div class="About">
        <p>Some people like to read on a screen. Other people need the variety and artistry, the sight, smell, and
            feel
            of
            actual books.They love seeing them on their shelves; they love having shelves for them.

            They love taking them along when they leave the house, and stacking them by their bedsides. They love
            finding
            old letters and bookmarks in them. They like remembering where they bought them or who they received
            them
            from.

            They want to read in a way that offers a rich experience, more than the words only: the full offering of
            a
            book.
            They are particular about covers, they want to surround themselves with the poetry of good design.

            They can't pass a bookstore without going in and getting something, they keep a library card and use it.

            They are allergic to cheap bestsellers; they delight in the out-of-the-way and the rare, the well-made
            and
            the
            hard-to-accomplish. They take care of their books; they know a book is only theirs until it passes on to
            someone
            else. They are good stewards of a timeless object.

            These are the people we're working for.
        </p>
    </div>
</div>
{% endblock %}

ecommerce_shop_project/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bookworm - the bookshop</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    {% block extrastyle %}
    {% endblock %}
    <link href="{% static 'css/shop.css' %}" rel="stylesheet">
    <link href="{% static 'css/about.css' %}" rel="stylesheet">
    <link href="{% static 'css/stars.css' %}" rel="stylesheet">
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'shop:index' %}">Bookworm</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'shop:index' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'shop:about' %}">About</a>
                    <a class="nav-item nav-link" href="{% url 'contact:contact' %}">Contact</a>
                    <a class="nav-item nav-link" href="{% url 'subscription:subscription' %}">Newsletter</a>
                </div>
                <div class="search-nav">
                    <form action="." method="get">
                        <input type="text" name="q" class="search" value="{% if query %}{{ query }}{% endif %}">
                        <button type="submit" class="btn-dark">Search</button>
                        {% if query %}
                        <button type="submit" formmethod="post" class="close-icon" name="clear-button"></button>
                        {% csrf_token %}
                        {% endif %}
                    </form>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <button class="btn btn-info pull-right">
                        {% with totail_items=cart|length %}
                        {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item{{ totail_items|pluralize }}, $ {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                        {% endif %}
                        {% endwith %}

                    </button>

                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'account:profile'%}">
                        Your profile
                    </a>
                    {% if user.is_staff %}
                    <a class="nav-item nav-link" href="{% url 'staff:panel'%}">
                        Staff panel
                    </a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{% url 'account:logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'account:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'account:register' %}">Register</a>
                    {% endif %}


                </div>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="row">


            {% block content%}


            {% endblock%}

        </div>
        <!-- /.row -->

    </div>

    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Bookworm 2019</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.0.min.js"
        integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

ecommerce_shop_project/shop/templates/shop/categories.html
<div class="col-lg-3">



    <ul class="category-menu list-group">
        {% for cat in category_list %}
        <a href="{{cat.get_absolute_url}}">
            <li
                class="list-group-item list-group-item-light {% if view.kwargs.name == cat.name or product.category.name == cat.name %}active{% endif %}">
                {{cat.name}}</li>
        </a>

        {% endfor %}
    </ul>

</div>

ecommerce_shop_project/shop/templates/shop/category_products.html
{% extends 'shop/base.html' %}
{% block content%}

{% include 'shop/categories.html' %}

<div class="col-lg-9">

    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row">
        {% if products %}
        {% for product in products %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <a href="{{ product.get_absolute_url }}">
            {% with cover=product.images.first %}
                {% if cover %}
                    <img class="card-img-top" src="{{cover.image.url}}" alt="" width="250" height="380">
                {% else %}
                    <img class="card-img-top" src="http://i.imgflip.com/31a3mt.jpg" alt="" width="250" height="380">
                {% endif %}
            {% endwith %}
                </a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    </h4>
                    {% if product.on_sale %}
                    <div class="product-on-sale-price">
                        <h6>${{ product.original_price }}</h6>
                        <h4>${{ product.price }} SALE!</h4>
                    </div>
                    {% else %}
                    <div class="product-price ">
                        <h5>${{ product.price }}</h5>
                    </div>
                    {% endif %}
                    <p class="card-text">{{ product.description|truncatewords:7}}</p>
                </div>
                <div class="card-footer">
                    {% if product.count_rating %}
                    <span class="text-muted">
                        {% for s in product.stars %}
                        &#9733;
                        {% endfor %}
                        {% for s in product.empty_stars %}
                        &#9734;
                        {% endfor %}
                        {% else %}
                        This product is not rated
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}

        <div class="col">
            <div class="card">
                <h3>There are no products in {{category.name}} category</h3>
            </div>

        </div>

        {% endif %}
    </div>
    {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
    {% endif %}

</div>
<!-- /.col-lg-9 -->


{% endblock%}

ecommerce_shop_project/shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}


{% include 'shop/categories.html' %}

<head>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" type="text/css" rel="stylesheet">
    <link href="{% static 'css/stars.css' %}" rel="stylesheet">
</head>

<div class="col-lg-9">

    <div class="card mt-4 product-info">
        {% for image in product.images.all %}
            <img class="card-img-top img-fluid cover-image" src="{{image.image.url}}" alt="" width="250" height="380">
        {% endfor %}
        <div class="card-body">
            <h3 class="card-title">{{ product.name }}</h3>
            {% if product.on_sale %}
            <div class="product-on-sale-price">
                <h6>${{ product.original_price }}</h6>
                <h4>${{ product.price }} SALE!</h4>
            </div>
            {% else %}
            <div class="product-price ">
                <h5>${{ product.price }}</h5>
            </div>
            {% endif %}

            <button id="likes1" {% if not user.is_authenticated %} disabled {% endif %} data-id="{{product.id}}" class="btn btn-danger fa fa-heart" type="button">
                {% if product.likes > 0 %} {{ product.likes }} {% endif %}
            </button>
            <p class="card-text">{{ product.description}}</p>

            <span class="ratings text-warning {% if user.is_authenticated %} clickable {% endif %}">
            {% if product.count_rating %}
                {% for s in stars %}
                    <span data-star="{{s}}" data-id="{{product.id}}">
                        &#9733;
                    </span>
                {% endfor %}
                {% for s in empty_stars %}
                    <span data-star="{{s|add:rating}}" class="empty-star" data-id="{{product.id}}">
                        &#9733;
                    </span>
                {% endfor %}
            {% else %}
                {% for i in empty_stars %}
                    <span data-star="{{i}}" class="text-dark" data-id="{{product.id}}">
                        &#9733;
                    </span>
                {% endfor %}
                </span>
                <span class="not_rated">This product is not rated</span>
            {% endif %}


            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                <div id="field">
                    {{ cart_product_form }}
                </div>
                <input type="submit" value="add to cart" class="btn btn-primary">
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-9">
            <div class="page-header">
                {% with comments.count as total_comments %}
                <small class="pull-right">{{ total_comments }} comments</small>
                {% endwith %}
            </div>
            <div class="comments-list">
                {% for comment in comments %}
                {% if comment.is_active %}
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading user_name">{{ comment.user }}</h4>
                        <div class="body-text">{{comment.body}}</div>
                    </div>
                </div>
                {% elif  user.id == comment.user_id and not comment.is_active %}
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading user_name">{{ comment.user }}</h4>
                        <small>Your comment is not publushed yet.</small>
                        <form class="comment-{{comment.pk}}"
                            action="{% url 'shop:edit_comment' comment_pk=comment.pk %}" method="POST">
                            {% csrf_token %}
                            <input type="text" name="body" value="{{comment.body}}" class="hidden body-input">
                            <div class="body-text">{{comment.body}}</div>

                            <input type="submit" value="save" class="hidden submit-button">
                            <input type="button" value="edit" class=" edit-button"
                                onclick="switchVisibiliy({{comment.pk}})">



                        </form>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% if user.is_authenticated %}
            <div class="media">
                <div class="media-body">
                    <form method="POST" action="{% url 'shop:add_comment' product_pk=product.pk %}">
                        {% csrf_token %}
                        {{ form|crispy}}
                        <input class="btn btn-info" type="submit" value="Add">
                    </form>
                </div>
            </div>
            {% endif %}

        </div>
    </div>

    <!-- /.card -->

</div>
<!-- /.col-lg-9 -->

<script>
    function switchVisibiliy(comment_pk) {
        form = document.querySelector(".comment-" + comment_pk);
        form.querySelector(".body-text").classList.toggle('hidden');
        form.querySelector(".body-input").classList.toggle('hidden');
        form.querySelector(".submit-button").classList.toggle('hidden');
        form.querySelector(".edit-button").classList.toggle('hidden');
    }
</script>
<script>
document.querySelectorAll(".clickable > span " ).forEach(s => s.addEventListener("mouseover", () => {
const star = $(event.target);
star.addClass("hover");
star.prevAll().addClass("hover");
}));

document.querySelectorAll(".clickable > span " ).forEach(s => s.addEventListener("mouseout", () => {
const star = $(event.target);
star.removeClass("hover");
star.prevAll().removeClass("hover");
}));

</script>

<style>
.empty-star {
color: black;
}

.hover {
color: #ffc107!important;
}

.ratings > span {
cursor: default;
}

.clickable > span {
cursor: pointer;
}


</style>
<script src="https://code.jquery.com/jquery-3.4.0.min.js"
    integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
{% csrf_token %}
<script type="text/javascript">
    // using jQuery
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
</script>
{% block extrajs %}
<script src="{% static 'js/like_button.js' %}"></script>
<script src="{% static 'js/stars.js' %}"></script>

{% endblock%}
{% endblock%}