ecommerce_shop_project/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<product_id>/", views.cart_add, name="cart_add"),
    path("remove/<product_id>/", views.cart_remove, name="cart_remove"),
]

ecommerce_shop_project/ecommerce_shop_project/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("cart", include("cart.urls")),
    path("contact/", include("contact.urls")),
    path("", include(("shop.urls", "shop"), namespace="shop")),
    path("account/", include(("account.urls", "account"), namespace="account")),
    path("staff/", include(("staff.urls", "staff"), namespace="staff")),
    path('orders/', include('orders.urls')),
    path('dynamic_cart/', include("dynamic_cart.urls")),
    path('subscription/', include('subscription.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ecommerce_shop_project/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path("create/<uuid:address_uuid>/", views.order_create, name="order_create"),
    path("new_address/", views.AddressCreateView.as_view(), name="new_address"),
]

ecommerce_shop_project/orders/models.py
from django.db import models
from shop.models import Product
from account.models import Address, User


class Order(models.Model):

    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return "Order {}".format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="order_items", on_delete=models.CASCADE
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return "{}".format(self.id)

    def get_cost(self):
        return self.price * self.quantity

ecommerce_shop_project/orders/forms.py
from django import forms
from .models import Order
from account.models import Address


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["address"]

    def __init__(self, *args, address_uuid=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if address_uuid:
            self.fields["address"].queryset = Address.objects.filter(uuid=address_uuid)
        elif user:
            self.fields["address"].queryset = Address.objects.filter(user=user)

    address = forms.ModelChoiceField(
        queryset=Address.objects.none(), widget=forms.RadioSelect, empty_label=None
    )


class AddressCreateForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            "name",
            "phone",
            "street",
            "city",
            "province",
            "postal_code",
            "country",
        ]

    def __init__(self, *args, **kwargs):
        logged = kwargs.pop("logged", None)
        super().__init__(*args, **kwargs)
        # If user is anonymous add email field
        if not logged:
            self.fields["email"] = forms.EmailField()

ecommerce_shop_project/orders/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.http import HttpResponseRedirect

from .models import OrderItem
from .forms import OrderCreateForm, AddressCreateForm
from cart.cart import Cart
from .tasks import order_created
from account.models import Address, User


def order_create(request, address_uuid=None):
    cart = Cart(request)
    if request.method == "POST":
        if request.user.is_authenticated:
            form = OrderCreateForm(request.POST, user=request.user)
        elif address_uuid:
            form = OrderCreateForm(request.POST, address_uuid=address_uuid)
        else:
            form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = order.address.user
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            cart.clear()
            order_created.delay(order.id)
            return render(request, "orders/order/created.html", {"order": order})
    else:
        if request.user.is_authenticated:
            form = OrderCreateForm(user=request.user)
        elif address_uuid:
            form = OrderCreateForm(address_uuid=address_uuid)
        else:
            form = OrderCreateForm()
    return render(request, "orders/order/create.html", {"form": form})


class AddressCreateView(CreateView):
    model = Address
    template_name = "orders/order/new_address.html"
    form_class = AddressCreateForm

    def get_success_url(self):
        if self.request.user.is_authenticated:
            return reverse_lazy("orders:order_create")
        else:
            return reverse_lazy(
                "orders:order_create", kwargs={"address_uuid": self.object.uuid}
            )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["logged"] = self.request.user.is_authenticated
        return kwargs

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
            self.object = form.save()

        else:  # If user is anonymous get or create non_active account
            email = form.cleaned_data["email"]
            user = User.objects.filter(email=email).first()
            if not user:
                user = User(email=email, is_active=False)
                user.set_password("pass")
                user.save()
            form.instance.user = user
            form.cleaned_data.pop("email", None)
            # get address if exists, otherwise create
            address = Address.objects.filter(user=user, **form.cleaned_data).first()
            if not address:
                self.object = form.save()
            else:
                self.object = address
        return HttpResponseRedirect(self.get_success_url())

ecommerce_shop_project/orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Your Shopping Cart| Checkout
{% endblock %}

{% block content %}

<div class="container">
    <div class="row" style="margin: 4%">
        <div class="col-md-8">
            <h4 class="page-header">Checkout</h4>
            <a href="{% url 'orders:new_address' %}">Add new address</a>
            <form action="." method="post">
                {% csrf_token %}
                {{ form|crispy}}
                <input type="submit" class="btn btn-primary" value="Submit order">
            </form>
        </div>
        <div class="col-md-4">
            <div class="page-header">
                Your Order
            </div>
            <ul class="list-group">
                {% for item in cart %}
                <li class="list-group-item">
                    {{ item.quantity }}x {{ item.product.name }}
                    <span> $ {{ item.total_price }}</span>
                </li>
                {% endfor %}

                <li class="list-group-item active">Total Cost: $ {{ cart.get_total_price }}</li>
            </ul>

        </div>
    </div>
</div>


{% endblock %}

ecommerce_shop_project/orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}

ecommerce_shop_project/orders/templates/orders/order/new_address.html
{% extends 'shop/base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class='profile-edit'>
                        <h2>Add address</h2>
                        <a href="{% url 'orders:order_create' %}" class="btn btn-info">Go back</a>

                        <form method="POST" style="padding:15px;">
                            {% csrf_token%}
                            <fieldset>
                                {{ form|crispy }}
                            </fieldset>
                            <div>
                                <button type="submit" class="btn btn-primary">Add</button>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}