ecommerce_shop_project/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<product_id>/", views.cart_add, name="cart_add"),
    path("remove/<product_id>/", views.cart_remove, name="cart_remove"),
]

ecommerce_shop_project/ecommerce_shop_project/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls, name="admin"),
    path("cart", include("cart.urls")),
    path("contact/", include("contact.urls")),
    path("", include(("shop.urls", "shop"), namespace="shop")),
    path("account/", include(("account.urls", "account"), namespace="account")),
    path("staff/", include(("staff.urls", "staff"), namespace="staff")),
    path('orders/', include('orders.urls')),
    path('dynamic_cart/', include("dynamic_cart.urls")),
    path('subscription/', include('subscription.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ecommerce_shop_project/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("create/", views.order_create, name="order_create"),
    path("create/<uuid:address_uuid>/", views.order_create, name="order_create"),
    path("new_address/", views.AddressCreateView.as_view(), name="new_address"),
]

ecommerce_shop_project/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("product/<str:slug>/", views.product_detail, name="product_detail"),
    path(
        "category/<str:name>/",
        views.CategoryProductView.as_view(),
        name="category_product",
    ),
    path("edit_comment/<int:comment_pk>/", views.process_comment, name="edit_comment"),
    path("add_comment/<int:product_pk>/", views.process_comment, name="add_comment"),
    path("about/", views.about, name="about"),
    path("like_product/<product_id>", views.like_product, name="like_product"),
    path(
        "add_rating/<product_id>/<int:stars>", views.process_rating, name="add_rating"
    ),
]

ecommerce_shop_project/cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(max_value=99, min_value=1, label='', initial=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

ecommerce_shop_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd["quantity"], update_quantity=cd["update"])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CartAddProductForm(
            initial={"quantity": item["quantity"], "update": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

ecommerce_shop_project/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
<link href="{% static 'css/detail.css' %}" rel="stylesheet">
{% block title %}
Your Shopping Cart
{% endblock %}


{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #444444">
                            {{ totail_items }} item{{ totail_items|pluralize }}, $ {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
        <table class="table table-striped table-hover">
            <thead style="background-color: #5f788a">
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        {% with cover=product.images.first %}
                        {% if cover %}
                        <img class="card-img-top" src="{{cover.image.url}}" alt=""
                             style="height: 130px; width: auto">
                        {% else %}
                        <img class="card-img-top" src="https://imgflip.com/i/31a3mt" alt=""
                             style="height: 130px; width: auto">
                        {% endif %}
                        {% endwith %}
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        {% csrf_token %}
                        <div id="field">
                            <button type="button" id="sub" class="sub">-</button>
                            {{ item.update_quantity_form.quantity }}
                            <button type="button" id="add" class="add">+</button>
                        </div>
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update" class="btn btn-info">
                    </form>
                </td>
                <td>
                    <a href="{% url 'cart:cart_remove' product.id %}">Remove</a>
                </td>
                <td> $ {{ item.price }}</td>
                <td> $ {{ item.total_price }}</td>
            </tr>
            {% endwith %}
            {% endfor %}
            <tr style="background-color: #5f788a">
                <td><b>Total</b></td>
                <td colspan="4"></td>
                <td colspan="num"><b> $ {{ cart.get_total_price }}</b></td>
            </tr>
            </tbody>
        </table>
        <p class="text-right">
            <a href="{% url 'shop:index' %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Checkout</a>
        </p>
    </div>
</div>
<script
        src="https://code.jquery.com/jquery-3.4.0.min.js"
        integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
        crossorigin="anonymous"></script>
{% block extrajs %}
<script src="{% static 'js/quantity_buttons.js' %}"></script>
{% endblock %}
{% endblock %}